services:
  backend_v8:
    build:
      context: ./apps/backend
    container_name: portal_sdm_backend_v8
    restart: unless-stopped
    ports:
      - "3338:3333"
    volumes:
      - ./database.sqlite:/data/database.sqlite
      - ./apps/backend/.env:/app/.env
    environment:
      - DB_SOURCE=/data/database.sqlite
    networks:
      - bpr-network

networks:
  bpr-network:
    name: bpr_shared_network
    external: true
