services:
  backend_v9:
    build:
      context: ./apps/backend
    container_name: portal_sdm_backend_v9
    restart: unless-stopped
    ports:
      - "3339:3333"
    environment:
      - DB_SOURCE=/data/database.sqlite
      - PORT=3333
      - CORS_ORIGIN=*
    command: /bin/sh -c "while true; do npm start; sleep 2; done"
    volumes:
      - portal_sdmv3_v9_backend_data:/data
      - portal_sdmv3_v9_backend_uploads:/app/public
    networks:
      - bpr-network

networks:
  bpr-network:
    name: bpr_shared_network
    external: true

volumes:
  portal_sdmv3_v9_backend_data:
  portal_sdmv3_v9_backend_uploads:
