PRAGMA foreign_keys=OFF;
ATTACH DATABASE '/tmp/db_backup.sqlite' AS backup;
BEGIN TRANSACTION;

INSERT OR IGNORE INTO pegawai SELECT * FROM backup.pegawai;
INSERT OR IGNORE INTO pengguna SELECT * FROM backup.pengguna;
INSERT OR IGNORE INTO permintaan_cuti SELECT * FROM backup.permintaan_cuti;
INSERT OR IGNORE INTO penggajian SELECT * FROM backup.penggajian;
INSERT OR IGNORE INTO penilaian_kinerja SELECT * FROM backup.penilaian_kinerja;
INSERT OR IGNORE INTO kontrak SELECT * FROM backup.kontrak;
INSERT OR IGNORE INTO pelatihan SELECT * FROM backup.pelatihan;
INSERT OR IGNORE INTO riwayat_jabatan SELECT * FROM backup.riwayat_jabatan;
INSERT OR IGNORE INTO tugas_orientasi SELECT * FROM backup.tugas_orientasi;
INSERT OR IGNORE INTO notifications SELECT * FROM backup.notifications;
INSERT OR IGNORE INTO users SELECT * FROM backup.users;
INSERT OR IGNORE INTO company_settings SELECT * FROM backup.company_settings;
INSERT OR IGNORE INTO data_change_requests SELECT * FROM backup.data_change_requests;
INSERT OR IGNORE INTO kandidat SELECT * FROM backup.kandidat;
INSERT OR IGNORE INTO analisis_beban_kerja SELECT * FROM backup.analisis_beban_kerja;
INSERT OR IGNORE INTO detail_beban_kerja SELECT * FROM backup.detail_beban_kerja;
INSERT OR IGNORE INTO activity_library SELECT * FROM backup.activity_library;
INSERT OR IGNORE INTO kpi_targets SELECT * FROM backup.kpi_targets;
INSERT OR IGNORE INTO jabatan SELECT * FROM backup.jabatan;
INSERT OR IGNORE INTO pinjaman_karyawan SELECT * FROM backup.pinjaman_karyawan;
INSERT OR IGNORE INTO organizational_kpi SELECT * FROM backup.organizational_kpi;
INSERT OR IGNORE INTO department_kpi SELECT * FROM backup.department_kpi;
INSERT OR IGNORE INTO assigned_tasks SELECT * FROM backup.assigned_tasks;
INSERT OR IGNORE INTO api_keys SELECT * FROM backup.api_keys;
INSERT OR IGNORE INTO integration_logs SELECT * FROM backup.integration_logs;
INSERT OR IGNORE INTO _migrations SELECT * FROM backup._migrations;
INSERT OR IGNORE INTO kpi_templates SELECT * FROM backup.kpi_templates;
INSERT OR IGNORE INTO audit_logs SELECT * FROM backup.audit_logs;
INSERT OR IGNORE INTO release_changelog SELECT * FROM backup.release_changelog;
INSERT OR IGNORE INTO kpi_nominal_targets SELECT * FROM backup.kpi_nominal_targets;
INSERT OR IGNORE INTO kredit_berkas SELECT * FROM backup.kredit_berkas;
INSERT OR IGNORE INTO kredit_berkas_tracking SELECT * FROM backup.kredit_berkas_tracking;
INSERT OR IGNORE INTO log_aktivitas_harian SELECT * FROM backup.log_aktivitas_harian;
INSERT OR IGNORE INTO wa_notification_log SELECT * FROM backup.wa_notification_log;
INSERT OR IGNORE INTO absensi SELECT * FROM backup.absensi;
INSERT OR IGNORE INTO arsip_dokumen SELECT * FROM backup.arsip_dokumen;
INSERT OR IGNORE INTO holidays SELECT * FROM backup.holidays;
INSERT OR IGNORE INTO daily_activities SELECT * FROM backup.daily_activities;

COMMIT;
DETACH DATABASE backup;
PRAGMA foreign_keys=ON;
