import { Router } from 'express';
import authRoutes from '../modules/pengguna/auth.routes';
import penggunaRoutes from '../modules/pengguna/pengguna.routes';
import employeeRoutes from '../modules/pegawai/pegawai.routes';
import leaveRoutes from '../modules/cuti/cuti.routes';
import attendanceRoutes from '../modules/absensi/absensi.routes';
import performanceRoutes from '../modules/kinerja/kinerja.routes';
import payrollRoutes from '../modules/penggajian/penggajian.routes';
import dataChangeRequestRoutes from '../modules/permintaanPerubahanData/permintaanPerubahanData.routes';
import recruitmentRoutes from '../modules/perekrutan/perekrutan.routes';
import onboardingRoutes from '../modules/orientasi/orientasi.routes';
import notificationRoutes from '../modules/notifikasi/notifikasi.routes';
import contractRoutes from '../modules/kontrak/kontrak.routes';
import pelatihanRoutes from '../modules/pelatihan/pelatihan.routes';
import backupRoutes from '../modules/backup/backup.routes';
import companySettingsRoutes from '../modules/company-settings/company-settings.routes';
import reportRoutes from '../modules/laporan/laporan.routes';
import dashboardRoutes from '../modules/dashboard/dashboard.routes';
import uploadRoutes from './upload';
import workloadRoutes from '../modules/workload/workload.routes';
import activityLibraryRoutes from '../modules/activity-library/activity-library.routes';
import kpiRoutes from '../modules/kpi/kpi.routes';
import kpiTemplateRoutes from '../modules/kpi/kpiTemplate.routes';
import jabatanRoutes from '../modules/jabatan/jabatan.routes';
import logAktivitasHarianRoutes from '../modules/log-aktivitas-harian/log-aktivitas-harian.routes';
import taskRoutes from '../modules/task/task.routes';
import integrationRoutes from '../modules/integration/integration.routes';
import auditLogRoutes from '../modules/audit-log/audit-log.routes';
import changelogRoutes from '../modules/changelog/changelog.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', penggunaRoutes);
router.use('/employees', employeeRoutes);
router.use('/leave-requests', leaveRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/performance-reviews', performanceRoutes);
router.use('/payrolls', payrollRoutes);
router.use('/data-change-requests', dataChangeRequestRoutes);
router.use('/recruitment', recruitmentRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/notifikasi', notificationRoutes);
router.use('/contracts', contractRoutes);
router.use('/pelatihan', pelatihanRoutes);
router.use('/backup', backupRoutes);
router.use('/company-settings', companySettingsRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/workload', workloadRoutes);
router.use('/activity-library', activityLibraryRoutes);
router.use('/kpi-targets', kpiRoutes);
router.use('/kpi-templates', kpiTemplateRoutes);
router.use('/jabatan', jabatanRoutes);
router.use('/log-aktivitas-harian', logAktivitasHarianRoutes);
router.use('/tasks', taskRoutes);
router.use('/integrations', integrationRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/changelog', changelogRoutes);
router.use('/', uploadRoutes);
export default router;
